// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/words.ts";
import * as $3 from "./routes/api/words/[wordId].ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/word/[word].tsx";
import * as $$0 from "./islands/NewWord.tsx";
import * as $$1 from "./islands/WordDetail.tsx";
import * as $$2 from "./islands/WordList.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/words.ts": $2,
    "./routes/api/words/[wordId].ts": $3,
    "./routes/index.tsx": $4,
    "./routes/word/[word].tsx": $5,
  },
  islands: {
    "./islands/NewWord.tsx": $$0,
    "./islands/WordDetail.tsx": $$1,
    "./islands/WordList.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
